# Generated by Django 4.0.5 on 2022-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('home_phone', models.IntegerField(blank=True, null=True)),
                ('work_phone', models.IntegerField(blank=True, null=True)),
                ('home_other', models.IntegerField(blank=True, null=True)),
                ('mobile_primary', models.IntegerField(blank=True, null=True)),
                ('mobile_secondary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
